### ISSUE TITLE
Why do we enforce a `forceFlush` method on Tracer?

### ISSUE THREAD

**Issue by fabianfett** [apple/swift-distributed-tracing#102]
Currently we enforce a `forceFlush` method on Tracer? The TracingSystem never calls this? Why do we enforce it then?

**Comment by ktoso** [comment]
In order to allow otel implementations to do this: https://opentelemetry.io/docs/reference/specification/trace/sdk/#forceflush

You may want to force flush on a tracer before you shutdown your process; it matters for graceful shutdown scenarios. We'll be keeping it.
