### ISSUE TITLE
Rename TracerProtocol to Trackable

### ISSUE THREAD

**Issue by fitomad** [apple/swift-distributed-tracing#104]
The `Protocol` suffix in the `TracerProtocol` protocol's name is redundant in this case and brings unnecessary information.

## Suggestion

Remove the `Protocol` suffix renaming the protocol to `Trackable`. 

The same case could be applied to the `LegacyTracerProtocol` protocol.
In that case, the protocol name becomes `LegacyTrackable`.

**Comment by ktoso** [comment]
Thanks for the feedback but it's a bit more complex than that.

The protocol suffix is a standard pattern when we need the proper name for a namsespace which we do here: `enum Tracer`

HOWEVER, we just worked out that we can lift functions into free functions and it'll work just as fine so we'll be recovering the `protocol Tracer`. 

I'll close this as a duplicate of: https://github.com/apple/swift-distributed-tracing/issues/109

**Comment by ktoso** [comment]
Duplicate of Duplicate: https://github.com/apple/swift-distributed-tracing/issues/109

**Comment by ktoso** [comment]
Solved in: https://github.com/apple/swift-distributed-tracing/pull/113

**Comment by fitomad** [comment]
> Thanks for the feedback but it's a bit more complex than that.
> 
> The protocol suffix is a standard pattern when we need the proper name for a namsespace which we do here: `enum Tracer`
> 
> HOWEVER, we just worked out that we can lift functions into free functions and it'll work just as fine so we'll be recovering the `protocol Tracer`.
> 
> I'll close this as a duplicate of: #109

Thanks for the explanation
