### ISSUE TITLE
Remove SpanStatus CanonicalCode

### ISSUE THREAD

**Issue by slashmo** [apple/swift-distributed-tracing#29]
OpenTelemetry deprecated GRPC-like status codes a while ago. We might want to remove them from our API as well:

**Current spec**
https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md#set-status

**Change in `.proto` file**
https://github.com/open-telemetry/opentelemetry-proto/commit/59c488bfb8fb6d0458ad6425758b70259ff4a2bd#diff-5c407ac9c675a60170f94ab620f5329f25e5388d6790864b7799abce66f79332

*This commit also added backwards-compatibility notes we might want to follow.*

**Comment by slashmo** [comment]
@ktoso What do you think about this? As far as I know, no (Swift) tracer has made use of these canonical codes anyways.

**Comment by slashmo** [comment]
FYI @pokryfka

**Comment by pokryfka** [comment]
Xray does have equivalent, but it does not matter really, it can be set using Xray interface if needed to.
The less requirements in the swift-distributed-tracing protocols the better, IMO.

**Comment by ktoso** [comment]
Excellent -- yes the simpler the interface the better. Just unset/ok/error sounds good to me.

**Comment by ktoso** [comment]
> Xray does have equivalent, but it does not matter really, it can be set using Xray interface if needed to.

I mean... it _can't_ in a library like http client, so the question if just nil/ok/error is valid. 

but simplifying here seems good to me in any case, let's do it.

**Comment by slashmo** [comment]
> I guess status: SpanStatus? enum SpanStatus { case ok ; case error } would be okey
> @ktoso
Ups, didn't see that comment earlier. Yeah, this sounds good. That way a Tracer can also semantically default to `unset` when set to `nil` (i.e. the default) and doesn't have to set `unset` by default itself.
