### ISSUE TITLE
withSpan() doesn’t work as documented

### ISSUE THREAD

**Issue by JensAyton** [apple/swift-distributed-tracing#30]
The documentation comments clearly state:

> DO NOT `end()` the passed in span manually. It will be ended automatically when the `function` returns.

However, there is no `end()` on the happy path, only if an error occurs.

Of course I could make a PR, but when I encountered this I convinced myself that such an obvious omission _might_ be intentional. :-)

**Comment by ktoso** [comment]
Thanks for spotting this! Bug indeed 🐞

**Comment by slashmo** [comment]
> Of course I could make a PR
> @JensAyton 

Thanks for the bug report! Would you like to take this on yourself?
