### ISSUE TITLE
Verify OpenTelemetry 1.0.0 compatibility

### ISSUE THREAD

**Issue by slashmo** [apple/swift-distributed-tracing#32]
Lots has happened in the OpenTelemetry specification since we defined our top-level Tracing API. Now that their [Trace API froze](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/api.md), we should go over it once again to check if our API is compatible.

For [0.2.0](https://github.com/apple/swift-distributed-tracing/milestone/3), we want to ensure that we're on par with [OTel 1.0.0](https://github.com/open-telemetry/opentelemetry-specification/releases/tag/v1.0.0).

**OpenTelemetry: [Definition of "FeatureFreeze"](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/document-status.md)**
> Document is no longer accepting new substantial changes, except when such changes are necessary to resolve a fundamental problem or inconsistency in the specification. Editorial changes are accepted. The document and the area it describes are considered feature-complete for the version of the specification the document targets. The document in this status is ready for implementation.

- [ ] #39
- [ ] #45
- [ ] #48

**Comment by ktoso** [comment]
Thanks @slashmo ! I'm going to close this in favor of the 3 specific tasks opened up here
