### ISSUE TITLE
Span.recordError should take optional SpanAttributes

### ISSUE THREAD

**Issue by slashmo** [apple/swift-distributed-tracing#45]
[The OTel specification states](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#record-exception) that Span’s `recordException` (in our case `recordError`) should take an additional argument to optionally specify `SpanAttributes`. These additional attributes (in case of OTel) are then merged into the resulting event’s attributes.

> If RecordException is provided, the method MUST accept an optional parameter to provide any additional event attributes (this SHOULD be done in the same way as for the AddEvent method). If attributes with the same name would be generated by the method already, the additional attributes take precedence.

**Comment by ktoso** [comment]
Good catch!
