### ISSUE TITLE
Possible unnecessary setting of Baggage task local variable

### ISSUE THREAD

**Issue by adam-fowler** [apple/swift-distributed-tracing#77]
Not sure if I'm missing something here but the `withSpan<T>(:ofKind:function:file:line:)` function doesn't edit the baggage so why is the task local variable being set inside the function. 
https://github.com/apple/swift-distributed-tracing/blob/1eb0a481b9416c4b86b40a41f478a2052c7bd9fe/Sources/Tracing/Tracer.swift#L224-L244

**Comment by adam-fowler** [comment]
Ok I think I get it now. Although you initialise the span with one set of baggage it will add its own keys to this baggage and the edited baggage will be set on the span.

**Comment by ktoso** [comment]
That's a great explanation by @slashmo, that's all correct. Yes, you give a baggage to startSpan, but the baggage it then sets is different - e.g. it might have have a new span-id of the new child span, but the same trace-id (depending on specific tracing system and how it uses identifiers etc.) Usually it'd also _keep_ all other baggage values so it is adding stuff there, not making a new baggage -- this way multiple baggage propagated values make their way through to child spans :-)
