### ISSUE TITLE
SpanAttributes subscript should use concrete type and not an existential

### ISSUE THREAD

**Issue by fabianfett** [apple/swift-distributed-tracing#82]
Currently `SpanAttributes` uses an existential for its subscript API. 

```swift
public struct SpanAttributes {
  public subscript(_ name: String) -> SpanAttributeConvertible? { get set }
}
```

Swift Logging uses the concrete type `Logger.Metadata.Value` instead:
```swift
public struct Logger {
    subscript(metadataKey metadataKey: String) -> Logger.MetadataValue? { get set }

    public enum MetadataValue {
        case string(String)
        case stringConvertible(CustomStringConvertible & Sendable)
        case dictionary(Metadata)
        case array([Metadata.Value])
    }
}
```

I think that we should change the SpanAttributes subscript API to return a `SpanAttribute`. This way this would work like Logging and we remove an existential from the API boundary

**Comment by ktoso** [comment]
Thanks for catching this -- here I think indeed we'll be able to do that 👀 Let's give it a shot.

**Comment by ktoso** [comment]
I'm not sure about this, it means we'd lose the ability to:

```
        span.attributes["http.status"] = response.status

```

which is very nice 🤔 I could not find a way around it.

**Comment by ktoso** [comment]
We can add additional API though, I'll do that
